#!/bin/bash
# SOURCE Bashstyling (https://github.com/iesextremadura/sh/blob/master/styles)
source <(curl -s https://raw.githubusercontent.com/iesextremadura/sh/master/styles)

h1 "Comprobamos que el plugin de adobe-flashplugin está instalado"

h1 "1. Comprobamos si el plugin está instalado"
if dpkg -l adobe-flashplugin
then 
    success "Ya está instalado"
    exit 0
else
    danger "No está instalado. Procedemos a la instalación"
fi


h1 "2. Vamos a comprobar que existe el repositorio en el sources.list"
if grep -Fxq "deb http://archive.canonical.com/ubuntu trusty partner" /etc/apt/sources.list
then
    # code if found
    success "Existe el repositorio. No hacemos nada."
else
    # code if not found
    danger "No existe el repositorio en el sources.list. Procedemos a añadirlo"
    echo "deb http://archive.canonical.com/ubuntu trusty partner" >> /etc/apt/sources.list
fi

h1 "3. Actualizamos apt"
apt-get -qq update

h1 "4. Instalamos el componente"
apt-get --yes --force-yes install adobe-flashplugin
if dpkg -l adobe-flashplugin
then 
    success "Se ha instalado correctamente"
    exit 0
else
    danger "No está instalado. Error en la instalación"
    exit 1
fi


